[theme]
base = "light"
primaryColor = "#0F2340"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#141B26"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
